#!/usr/bin/env python
from pprint import pprint
import botocore.session
import logging
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('').setLevel(logging.DEBUG)
s = botocore.session.get_session()
s3 = s.create_client('s3', 'us-west-2')
pprint(s3.list_buckets())
